name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build . -t gcr.io/${{ secrets.GCP_PROJECT }}/docker-repo/my-app:${{ github.sha }}
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/docker-repo/my-app:${{ github.sha }}
